### ISSUE TITLE
Experiments management

### ISSUE THREAD

**Issue by smacker** [src-d/code-annotation#160]
We need to allow to manage experiments by web ui:

 - [x] create endpoint to manage experiments POST #180
 - [x] create endpoints to manage experiments PUT #190
 - [x] create an endpoint to upload file pairs to experiment #188 
 - [x] create wireframes for UI
 - [x] create frontend for things above #195

**Comment by carlosms** [comment]
Hey @ricardobaeta we are ready to start working on the new front-end code to manage experiments. The new functionality, available only to Reviewers, is:

- Upload a DB file with file pairs to be added to a single experiment
- Create a new experiment: Name and Description can be provided
- Update the Name or Description of an existing experiment

Please let us know if you prefer to provide wireframes beforehand, or if it's better if we build something simple and then iterate the design with your input.
I imagine it could be similar to the current dashboard, with buttons to 'edit' 'add file pairs', and 'create new experiment'

**Comment by ricardobaeta** [comment]
Hey @carlosms The wireframes for this UI is in my to-do for today! Also, updated the description to include the wireframming.

**Comment by ricardobaeta** [comment]
@bzz @dpordomingo @smacker 

Thanks for the help @carlosms !

Here's the wireframe https://balsamiq.cloud/sdjen2c/puva1qi

**Comment by carlosms** [comment]
Thanks @ricardobaeta. Just to confirm, this wireframe shows the current dashboard with extra elements visible only to users with the right role, or should this be a separate page accessible from the menu?

**Comment by ricardobaeta** [comment]
> Just to confirm, this wireframe shows the current dashboard with extra elements visible only to users with the right role, or should this be a separate page accessible from the menu?

Let's make the experience as collaborative as we can. ```visible only to users with the right role``` Persona disclosure :)

**Comment by dpordomingo** [comment]
LGTM, but instead of «survey» I'd use «experiment»:

I'd also clarify in the upload section that the uploaded data will be **added** to the current one.

![image](https://user-images.githubusercontent.com/2437584/36980444-8cc476a8-208a-11e8-8ab5-8e7c13789ab1.png)

I say so because the button says «upload new file», what can be understood as replacing current data with new one. What about if the button says: «add more file pairs», for example...

**Comment by ricardobaeta** [comment]
> but instead of «survey» I'd use «experiment»

The correct semantic expression is *survey*. Articulated in the past with @vmarkovtsev and @marnovo  

> and I'd clarify in the upload section that the uploaded data will be added to the current one.
> I say so because the button says «upload new file», what can be understood as replacing current 
> data with new one. What about if the button says: «add more file pairs», for example...

**upload new file** allows logic engagement on both contextual behaviours. The one upon **Edit** & **New**. Saying that people can upload a new file to the survey, is suited for when they have or don't have a previous file. New file is clear, a new one - agnostic to whereas is a replacement or an addition.

Nevertheless, we **should** display on the screen the name of the file after upload. I think it's pretty valuable. 

Thank you for the product savvy feedback, good ux is good copy.

**Comment by dpordomingo** [comment]
Considering our current [Design Document](https://docs.google.com/document/d/1EJWd0-DXV9W-NveJBCn9I1DWhTsEKQwZEOJNClkUSRw), I found no mentions to "survey" but a lot of mentions to "experiment".

In the current dashboard it's also used the "experiment" term:

![image](https://user-images.githubusercontent.com/2437584/36980303-38c7834c-208a-11e8-9af6-288769ac4b47.png)

and also in our site urls: https://code-annotation-staging.srcd.run/exp/1/3962

We should maybe unify our terminology.

**Comment by ricardobaeta** [comment]
@marnovo Could you please be so kind to elaborate on this? ☝️

**Comment by carlosms** [comment]
Closing this one, all PRs are merged.
If needed, further discussion about the UI can be done in a new issue.
