### ISSUE TITLE
Add UAST to old FilePairs

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#214]
As described by https://github.com/src-d/backlog/issues/1242#issuecomment-372313046 ML team needs:
- [x] new 500 pairs added to existing experiment on staging,
- [x] to be able to add more annotations for the research,
- [x] add UAST to the already existent FilePairs

In order to accomplish that :point_up: we should: :point_down: 
- obtain the new data from ML:
  - [x] add it into [gdrive](https://drive.google.com/drive/folders/11rOLFTJ67tj_Jst2wBRMxNFPcmKaO26q) &rarr; https://github.com/src-d/backlog/issues/1242#issuecomment-372313046
- prepare (and pull request) the migration scripts:
  - [x] **(A)** to add 2 UAST cols (nullable) to the `file_pairs` table, &rarr; https://github.com/src-d/code-annotation/pull/221
  - [x] **(B)** to add to each FilePair from our `file_pairs` table, the UAST stored in the ML DB, &rarr; https://github.com/src-d/code-annotation/pull/221
  - [x] **(C)** _(optional)_ to remove `diff` column since it is not longer needed (by https://github.com/src-d/code-annotation/pull/194), &rarr; https://github.com/src-d/code-annotation/pull/221
  - [x] ~~**(D)** _(optional)_ to add the 500 new FilePairs stored in the ML DB,~~
- proceed with the migration
  - [x] add into [gdrive](https://drive.google.com/drive/folders/11rOLFTJ67tj_Jst2wBRMxNFPcmKaO26q) the current internal DB &rarr; [infra#152](https://github.com/src-d/issues-infrastructure/issues/152),
  - [x] run the migration scripts locally over the downloaded DB, to obtain a new DB,
  - [x] add into [gdrive](https://drive.google.com/drive/folders/11rOLFTJ67tj_Jst2wBRMxNFPcmKaO26q) the internal DB obtained from the prev step &rarr; [infra#152](https://github.com/src-d/issues-infrastructure/issues/152),
  - [x] replace the current CAT internal DB, with the new one &rarr; [infra#152](https://github.com/src-d/issues-infrastructure/issues/152),

Notes:
- The different versions of the internal DB will be shared in:<br />[gdrive/engineering/applicationsdemo/code-annotation-databases/3-add-UAST](https://drive.google.com/drive/folders/11rOLFTJ67tj_Jst2wBRMxNFPcmKaO26q)
- All the migration scripts could be done "at once".
- The **(D)** migration script was not needed because the 500 new FilePairs were added using the new Experiments Manager

**Comment by dpordomingo** [comment]
_Issue desc update:_
The **(C)** migration script was not needed because the 500 new FilePairs were added using the new Experiments Manager

**Comment by dpordomingo** [comment]
done
