### ISSUE TITLE
Prepare and deploy Production environment

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#215]
In order to have a Production environment we need:
- Retrieve data:
  - [x] to know the HOSTNAME to be used for production,
  - [x] to create and communicate the new `GA_TRACKING_ID` for testing purposes &rarr; https://github.com/src-d/code-annotation/issues/216
  - [x] create a new GitHub OAuth application for prod, using Prod callback &rarr; https://github.com/src-d/code-annotation/issues/217
  - [x] to communicate to @src-d/infrastructure the secrets of the new GitHub OAuth application
- Prepare the environment:
  - [x] `.drone.yml` and helm charts &rarr; https://github.com/src-d/code-annotation/pull/218
- Deploy
  - [x] configure Kubernetes secrets &rarr; https://github.com/src-d/issues-infrastructure/issues/152
  - [x] stop the annotation process being done in Staging, &rarr; https://github.com/src-d/code-annotation/pull/237
  - [x] deploy CAT into Staging &rarr; unauthorizing all no @src-d/applications members,
  - [x] deploy CAT into Prod
- Create the Production internal DB 
  - [x] download, modify and upload the new version of the internal DB into Prod and Staging &rarr; https://github.com/src-d/code-annotation/issues/214
- Test and celebrate:
  - [x] configure GA pannels &rarr; https://github.com/src-d/code-annotation/issues/241
  - [x] notify CAT users that from now on it should be used the Production env,

**Comment by rporres** [comment]
hostname: **code-annotation.srcd.run**
ingress.globalStaticIpName: code-annotation-production

Helm chart is the same, only the values passed change

(hostname edited by @dpordomingo as agreed by https://github.com/src-d/code-annotation/issues/217#issuecomment-378615285)
