### ISSUE TITLE
Reviewer: new page on the frontend, showing ML-extracted features

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#47]
Implement a page, with the reviewer part of annotation tool.

This would require proposing a JSON format for backend, to be used in #44 and mocking the KV results, until backend endpoint  is in place.

 - [x] Add new page to the FE #57 
-  [x] Endpoint with results of annotations #88
 - [x] make this page use backend from #44
 - [x] add restrictions to backend endpoints & frontend router #124

~This would also require something like hard-coding a "reviewer" bit for some users inside the DB, as proper user and ACL is outside of the scope right now.~

ACL is handled in #60

**Comment by smacker** [comment]
the initial frontend is done. I believe for API side we have another issue, but just in case I'm moving this one back in to do.

**Comment by dpordomingo** [comment]
@smacker could you create an issue (or put it here) the specs of the new endpoints that will be needed to achieve this feature?

**Comment by bzz** [comment]
@dpordomingo AFAIK new endpoint is handled under #44 .

@smacker Initial work on FE is done in #57, so please, correct me if I'm wrong, but what's left under this issue is to make the page display the results from the API.

PR description updated.

**Comment by smacker** [comment]
yes. we all set for api with #44. Just need to make sure our existing API returns blob id and score from database.

**Comment by smacker** [comment]
done  🎉 further improvements will be handled in other issues

**Comment by bzz** [comment]
🎉 For the history, could you please also post the URL of the reviewer page here?

**Comment by smacker** [comment]
`http(s)://<UI-HOST>/review`
