### ISSUE TITLE
Prepare first release of code annotation

### ISSUE THREAD

**Issue by dpordomingo** [src-d/code-annotation#70]
### technical stuff
- loading initial data, options:
  - put the internal.db inside a volume, that will be `kubectl cp`ed by Rafa
    - [x] adding example.db https://github.com/src-d/issues-infrastructure/issues/129
    - [x] adding our real data
  - ~~deliver the database inside of the image~~
  - ~~Rafa access the container, pull the data and run the export~~
- [x] #69 make sure that the server won't panic if it is launched without a DB
  - (nice to have) the server will init the DB if it does not exist
- [x] the server will use the db inside the volume:
  - the path of the DB will be a default value, and should point to `/var/...`
  - that path should be hardcoded in the charts, to let them mount the volume properly
- deployment (Rafa tested and it works), but there are missing things:
  - [x] fix the Docker image #36 &rarr; #85
    - env values, urls...
  - [x] _Rafa_: configure drone https://github.com/src-d/code-annotation/pull/30#pullrequestreview-94810221
- [x] fix x509 error in /oauth-callback https://github.com/src-d/code-annotation/issues/98
- [x] tag 0.0.1 release and publish ~a binary at~ GH release _Update_: publishing artefacts it tracked under #159

### PRs that needs to be merged 
- [x] docs https://github.com/src-d/code-annotation/pull/29
- [x] db part https://github.com/src-d/code-annotation/pull/56
- [x] acl control https://github.com/src-d/code-annotation/pull/60
- [x] single binary https://github.com/src-d/code-annotation/pull/36
- [x] deploy #85

### GitHub configurations needed
 - [x] _Alex_: Create Application, generate OAuth tokens, communicate the secrets to infra team
 - [x] _Alex_: Create the new organization and teams (reviewers and workers), and add users to the teams.

## Next steps
- [x] Add a button to export data into volume <br />(_nice to have:_ serve the data right away) https://github.com/src-d/code-annotation/issues/73
- reviewer part
- let's decide how to rollback in the future, options:
  - kubectl command
  - tag a new version with old code
- being able to access the logs:
  - @rporres should explain how to proceed
- improve logging errors https://github.com/src-d/code-annotation/issues/50

**Comment by rporres** [comment]
_adding the internal db inside a volume, that will be kubectl cped by Rafa_

Please don't tell me the application will be writing in a db inside the container 😱 

And that does not play well with CI/CD. Why don't we create a volume and attach it to the container? I can give you advise on that.

**Comment by rporres** [comment]
As for the logs, @dpordomingo should have access. Please let me know if I'm right

**Comment by dpordomingo** [comment]
>_Why don't we create a volume and attach it to the container?_

That's the idea de purposed when we wrote:

>_adding the internal db inside a volume_

So our proposal is to mount a volume in the container, and put there the sqlite file. So the app won't write inside the container, but in the db that will be in the volume.

If we do so, the pending thing would be how to put there the initial dataset. That's because we suggested to scp it.

**Comment by rporres** [comment]
The chart doesn't have any volume attached, hence I didn't understand correctly. Happy to see that we're aligned 😄 Since we're in GCP, it's easy to add a volume using a [Persistent Volume Claim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)

Another important thing is to avoid creating deployments with more than 1 pod, for obvious reasons 😅 

Depending on the size of the dataset it can be a good or a bad idea to copy it through kubectl. What are we talking about?

**Comment by bzz** [comment]
@rporres 

> Depending on the size of the dataset it can be a good or a bad idea to copy it through kubectl. What are we talking about?

1.6 Gb

**Comment by rporres** [comment]
Then it's fine to copy it using `kubectl`

**Comment by bzz** [comment]
Took liberty of updating the PR description to the best of my knowledge of the current status.

Do we also need a separate issue for `adding our real data` for `kubectl cp` of 1.6 Gb under https://github.com/src-d/issues-infrastructure ?

**Comment by ricardobaeta** [comment]
@bzz Can I have the opportunity to do "Arte-Final" before the release? It would be work on less if need be. I need one hour to do this.

**Comment by dpordomingo** [comment]
@bzz the issue is prepared, but not opened (it's closed)
https://github.com/src-d/issues-infrastructure/issues/131

I'll re-open it once I ensured that authentication is working.
(I'm trying to debug why did it failed, and I could access with a non `src-d` user)

**Comment by bzz** [comment]
@ricardobaeta 
> Can I have the opportunity to do "Arte-Final" before the release?

we are rushing to have a deployment ASAP, but I would guess that making proper release would take at least 1 day more, so please take your time!

**Comment by bzz** [comment]
@dpordomingo any reason not to tag a release and 🍾  and close this guy?

**Comment by bzz** [comment]
Further release automation will be tracked under https://github.com/src-d/code-annotation/issues/159 PR description updated
